name: Humble Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - humble

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: humble
      ref: humble
      ros2_repo_branch: humble
