name: RHEL Humble Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble

jobs:
  humble_rhel_binary:
    name: Humble RHEL binary build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rhel-binary-build.yml@master
    with:
      ros_distro: humble
      upstream_workspace: ros2_controllers.humble.repos
      ref_for_scheduled_build: humble
      skip_packages: rqt_joint_trajectory_controller
