name: Iron Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - iron

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: iron
      ref: iron
      ros2_repo_branch: iron
