name: Debian Iron Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - iron


jobs:
  iron_debian:
    name: Iron debian build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: iron
      upstream_workspace: ros2_controllers.iron.repos
      ref_for_scheduled_build: iron
      skip_packages: rqt_joint_trajectory_controller
