name: Rolling Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: rolling
      ref: master
      ros2_repo_branch: rolling
