name: Debian Rolling Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master


jobs:
  rolling_debian:
    name: Rolling debian build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: rolling
      upstream_workspace: ros2_controllers.rolling.repos
      ref_for_scheduled_build: master
      skip_packages: rqt_joint_trajectory_controller
